services:
  frontend:
    build: ./frontend
    container_name: transcendence_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "4000:4000"
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    depends_on:
      - auth-database
    stdin_open: true
    tty: true

  auth-database:
    image: postgres:15
    container_name: auth-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=auth-db
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

volumes:
  auth_db_data: